name: flutter_boiler_plate
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  progress_dialog: 1.2.1
  url_launcher: 5.4.2
  flutter_platform_widgets: 0.32.4
  logger: ^0.8.3
  validators: ^2.0.0+1
  flushbar: ^1.9.1
  timeago:
  vibrate: 0.0.4
  get_it: 4.0.4
  auto_route: 0.6.7
  connectivity: 0.4.8+2
  cached_network_image: ^2.2.0
  json_annotation: 3.0.1
  shimmer: 1.1.1
  package_info: ^0.4.0+18
  fluttertoast: ^4.0.0
  smooth_page_indicator: 0.1.5
  freezed: 0.10.9
  flutter_bloc: 6.0.0
  provider: 4.3.1
  shared_preferences:
  floor: 0.14.0
  sqflite: 1.3.1
  dio: 3.0.10
  share: 0.6.4+3
  cupertino_icons: ^0.1.3
  agora_rtc_engine: 1.0.15
  permission_handler: ^3.0.0
  file_picker: 1.13.3
  hydrated_bloc: 6.0.1
  image_picker:
  photo_view: 0.10.2
  native_pdf_view: 3.8.0
  path_provider: 1.6.14
  stomp_dart_client: 0.3.6
  firebase_crashlytics: 0.1.4+1
  http: 0.12.0+4
  flutter_custom_tabs: 0.6.0
  flutter_svg:
  path_drawing: ^0.4.1
  vector_math: ^2.0.4
  meta: ^1.1.2
  grec_minimal: 0.0.3
  date_util: 0.1.4
  location: ^3.0.2
  geocoder: 0.2.1
  device_preview: 0.4.5
  #  razorpay_flutter: 1.2.1
  firebase_messaging:
  firebase_analytics: 5.0.15
  firebase_dynamic_links: 0.5.1
  flutter_local_notifications: 0.8.4
  flutter_icons: 1.1.0
  web_socket_channel:
  firebase_remote_config:



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.1
  json_serializable: ^3.2.3
  auto_route_generator: 0.6.6




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    #Images
    - assets/images/
    #Languages
    - i18n/


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 600
